name: Publish Latest

on:
  push:
   branches:
     - main

jobs:
  make:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          make beamer
          mv beamer.pdf hauptseminar-beamer.pdf
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Hauptseminar Präsentation.pdf
        path: hauptseminar-beamer.pdf
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 7
    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.short-sha.outputs.sha }}
        artifacts: hauptseminar-beamer.pdf
