name: Publish Latest

on:
  push:
   branches:
     - main

jobs:
  make:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
    - uses: xu-cheng/texlive-action/full@v1
      with:
        run: |
          make beamer
          mv beamer.pdf hauptseminar-beamer.pdf
    - name: upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Hauptseminar Präsentation.pdf
        path: hauptseminar-beamer.pdf
    - uses: ncipollo/release-action@v1
      with:
        artifacts: hauptseminar-beamer.pdf
        allowUpdates: true
        tag: latest
